// Levels 4a / 4b with real media generated by ffmpeg, and non-HTTP protocols.
// Skipped when ffmpeg is not installed (CI installs it).

import assert from 'node:assert/strict';
import { after, before, describe, test } from 'node:test';
import { checkStream } from '../check.js';
import { hasFfmpeg, hlsMedia, mediaFixtures, send, startServer } from './helpers.js';

const skip = hasFfmpeg() ? false : 'ffmpeg chưa được cài';
const OPTS = { requestTimeoutMs: 3000, connectTimeoutMs: 1000, streamBudgetMs: 20000, retryDelayMs: 50, ffprobeTimeoutMs: 15000 };

describe('mức 4a / 4b (ffprobe, ffmpeg)', { skip }, () => {
  let srv;
  before(async () => {
    const { av, audio } = mediaFixtures();
    srv = await startServer({
      '/av.m3u8': send(200, hlsMedia(['av1.ts', 'av2.ts'])),
      '/av1.ts': send(200, av, { 'Content-Type': 'video/mp2t' }),
      '/av2.ts': send(200, av, { 'Content-Type': 'video/mp2t' }),
      '/master.m3u8': send(200, '#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=900000\nav.m3u8\n#EXT-X-STREAM-INF:BANDWIDTH=200000\nodd.m3u8\n'),
      // Segments without a standard extension (common on IPTV servers).
      '/odd.m3u8': send(200, hlsMedia(['chunk?id=1', 'chunk?id=2'])),
      '/chunk': send(200, av, { 'Content-Type': 'video/mp2t' }),
      '/radio.m3u8': send(200, hlsMedia(['a1.ts'])),
      '/a1.ts': send(200, audio),
      '/fake.m3u8': send(200, hlsMedia(['junk.ts'])),
      '/junk.ts': send(200, Buffer.alloc(4096, 0x47)),
      '/ua.m3u8': send(200, hlsMedia(['ua.ts', 'ua.ts'])),
      '/ua.ts': (req, res) => (req.headers['user-agent'] === 'MyPlayer/1.0' && req.headers.referer === 'https://site.example/'
        ? send(200, av)(req, res) : send(403, 'no')(req, res)),
      '/direct.ts': send(200, av, { 'Content-Type': 'video/mp2t' }),
    });
  });
  after(() => srv?.close());
  const url = (p) => `${srv.base}${p}`;

  test('4a: HLS có video + audio → ONLINE', async () => {
    const r = await checkStream({ url: url('/av.m3u8') }, '4a', OPTS);
    assert.equal(r.ok, true, JSON.stringify(r));
  });
  test('4a: master → variant thấp nhất; segment không có đuôi chuẩn vẫn đọc được', async () => {
    const before = srv.hits['/odd.m3u8'] || 0;
    const r = await checkStream({ url: url('/master.m3u8') }, '4a', OPTS);
    assert.equal(r.ok, true, JSON.stringify(r));
    assert.ok(srv.hits['/odd.m3u8'] - before >= 1);
  });
  test('4b: decode được 1 keyframe → ONLINE', async () => {
    const r = await checkStream({ url: url('/av.m3u8') }, '4b', OPTS);
    assert.equal(r.ok, true, JSON.stringify(r));
  });
  test('4b: stream chỉ có tiếng → decode 1 frame âm thanh', async () => {
    const r = await checkStream({ url: url('/radio.m3u8') }, '4b', OPTS);
    assert.equal(r.ok, true, JSON.stringify(r));
  });
  test('4a: dữ liệu rác → không tìm thấy hình/tiếng', async () => {
    const r = await checkStream({ url: url('/fake.m3u8') }, '4a', OPTS);
    assert.equal(r.ok, false);
    assert.ok(['NO_MEDIA_STREAM', 'INVALID_MEDIA'].includes(r.code), r.code);
  });
  test('4a: ffprobe gửi User-Agent và Referer của stream', async () => {
    const stream = { url: url('/ua.m3u8'), userAgent: 'MyPlayer/1.0', referrer: 'https://site.example/' };
    assert.equal((await checkStream(stream, '4a', OPTS)).ok, true);
    const without = await checkStream({ url: url('/ua.m3u8') }, '4a', { ...OPTS, allowRetry: false });
    assert.equal(without.ok, false);
  });
  test('4b: link TS trực tiếp → ONLINE', async () => {
    const r = await checkStream({ url: url('/direct.ts') }, '4b', OPTS);
    assert.equal(r.ok, true, JSON.stringify(r));
  });
  test('rtmp không kết nối được → CONNECTION_ERROR (ở mọi mức)', async () => {
    const r = await checkStream({ url: 'rtmp://127.0.0.1:1/live/stream' }, '2', { ...OPTS, allowRetry: false });
    assert.equal(r.code, 'CONNECTION_ERROR');
  });
  test('giao thức lạ → UNSUPPORTED_PROTOCOL', async () => {
    const r = await checkStream({ url: 'foo://example.com/live' }, '3', { ...OPTS, allowRetry: false });
    assert.equal(r.code, 'UNSUPPORTED_PROTOCOL');
  });
});
